### ISSUE TITLE
No rewards for more than 36 hours

### ISSUE THREAD

**Issue by argentocoin** [vantaur/vantaur#2]
My masternode has been ENABLED for 3d 14h:17m:13s and yet the las time I got a reward was at 3/2/2018 17:13 ... it doesn't make sense that even though the average is about 10h, that you go more than 36 hours without a reward.  This is one of the things that kills coins.  I think that the dev team has to update the wallet so that this stops happenning.

**Comment by cintrondigital** [comment]
Is your nodes ip on the list?

**Comment by vantaur** [comment]
Check to see if your masternodes IP is on the list. If so then check your VPS and do a `vantaurd masternode status` if the status code is 9, it's working.
